services:
    client:
        build: ./client
        ports:
            - 8080:3000
        command: yarn start
        volumes:
            - ./client/src/:/client/src
            - /app/node_modules

    server:
        build: ./server
        ports:
            - 5050:5000
        command: npm run dev
        volumes:
            - ./server/src/:/server/src

    mongodb:
        image: mongo
        volumes:
            - ./data:/data/db